paths:
  do_split: true
  manifest_path: "/home/xabierdetoro/xabi/tfm/gits/data/master_join.xlsx"
  model_name: "ser_model_join"
  model_dir: "/home/xabierdetoro/xabi/tfm/gits/scripts/models_results"
input:
  sample_rate: 16000
  duration: 3
train:
  aug_data: true
  max_epochs: 1500
  batch_size: 16
  patience: 15
  learning_rate: 0.005

num_classes: 4